//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerLock.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComputerLock.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少需要为密码框启用一种激活方式 的本地化字符串。
        /// </summary>
        public static string ActiveMethodEmpty {
            get {
                return ResourceManager.GetString("ActiveMethodEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级 的本地化字符串。
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外观 的本地化字符串。
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动检查更新 的本地化字符串。
        /// </summary>
        public static string AutoCheckUpdate {
            get {
                return ResourceManager.GetString("AutoCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无操作时自动锁定 的本地化字符串。
        /// </summary>
        public static string AutoLock {
            get {
                return ResourceManager.GetString("AutoLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定后自动执行 的本地化字符串。
        /// </summary>
        public static string AutoPower {
            get {
                return ResourceManager.GetString("AutoPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机时自动启动 的本地化字符串。
        /// </summary>
        public static string Autostart {
            get {
                return ResourceManager.GetString("Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左下 的本地化字符串。
        /// </summary>
        public static string BottomLeft {
            get {
                return ResourceManager.GetString("BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右下 的本地化字符串。
        /// </summary>
        public static string BottomRight {
            get {
                return ResourceManager.GetString("BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中 的本地化字符串。
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件路径异常 的本地化字符串。
        /// </summary>
        public static string ConfigFilePathError {
            get {
                return ResourceManager.GetString("ConfigFilePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前密码 的本地化字符串。
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色 的本地化字符串。
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前解锁方式：按 [ESC] 键 或 鼠标点击密码框位置显示密码框 的本地化字符串。
        /// </summary>
        public static string DisablePasswordBoxTips {
            get {
                return ResourceManager.GetString("DisablePasswordBoxTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序锁定时禁用 Windows 自动屏幕锁定 的本地化字符串。
        /// </summary>
        public static string DisableWindowsLock {
            get {
                return ResourceManager.GetString("DisableWindowsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过移动鼠标来防止 Windows 自动锁屏 的本地化字符串。
        /// </summary>
        public static string DisableWindowsRemark {
            get {
                return ResourceManager.GetString("DisableWindowsRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 屏幕锁定 的本地化字符串。
        /// </summary>
        public static string DoLock {
            get {
                return ResourceManager.GetString("DoLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持作者 的本地化字符串。
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示解锁密码框 的本地化字符串。
        /// </summary>
        public static string EnablePasswordBox {
            get {
                return ResourceManager.GetString("EnablePasswordBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前解锁方式：按 [ESC] 键，然后直接输入密码 的本地化字符串。
        /// </summary>
        public static string EnablePasswordBoxTips {
            get {
                return ResourceManager.GetString("EnablePasswordBoxTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用软件渲染 的本地化字符串。
        /// </summary>
        public static string EnableSoftwareRendering {
            get {
                return ResourceManager.GetString("EnableSoftwareRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认启用以减少内存占用。如遇动画卡顿，可尝试关闭以提升流畅度。 的本地化字符串。
        /// </summary>
        public static string EnableSoftwareRenderingRemark {
            get {
                return ResourceManager.GetString("EnableSoftwareRenderingRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请直接在键盘上输入新的快捷键 的本地化字符串。
        /// </summary>
        public static string EnterShortcutKey {
            get {
                return ResourceManager.GetString("EnterShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁屏快捷键注册失败: 的本地化字符串。
        /// </summary>
        public static string ExRegistFailed {
            get {
                return ResourceManager.GetString("ExRegistFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级 的本地化字符串。
        /// </summary>
        public static string General_Group_Advanced {
            get {
                return ResourceManager.GetString("General_Group_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渲染与外观 的本地化字符串。
        /// </summary>
        public static string General_Group_Appearance {
            get {
                return ResourceManager.GetString("General_Group_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志管理 的本地化字符串。
        /// </summary>
        public static string General_Group_Logs {
            get {
                return ResourceManager.GetString("General_Group_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动与窗口行为 的本地化字符串。
        /// </summary>
        public static string General_Group_Startup {
            get {
                return ResourceManager.GetString("General_Group_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通用设置 的本地化字符串。
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 休眠 的本地化字符串。
        /// </summary>
        public static string Hibernate {
            get {
                return ResourceManager.GetString("Hibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 秒后隐藏 的本地化字符串。
        /// </summary>
        public static string HideAfterXSecond {
            get {
                return ResourceManager.GetString("HideAfterXSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定时隐藏鼠标光标 的本地化字符串。
        /// </summary>
        public static string HideMouseCursor {
            get {
                return ResourceManager.GetString("HideMouseCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无操作时自动隐藏密码框 的本地化字符串。
        /// </summary>
        public static string HidePasswordWindow {
            get {
                return ResourceManager.GetString("HidePasswordWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭窗口时最小化到托盘 的本地化字符串。
        /// </summary>
        public static string HideWindowWhenClose {
            get {
                return ResourceManager.GetString("HideWindowWhenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按下 ESC 键后最小化到托盘 的本地化字符串。
        /// </summary>
        public static string HideWindowWhenEsc {
            get {
                return ResourceManager.GetString("HideWindowWhenEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动后最小化到托盘 的本地化字符串。
        /// </summary>
        public static string HideWindowWhenLaunch {
            get {
                return ResourceManager.GetString("HideWindowWhenLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用快捷键解锁 的本地化字符串。
        /// </summary>
        public static string HotkeyUnlock {
            get {
                return ResourceManager.GetString("HotkeyUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 屏幕锁定时停止程序锁定服务 的本地化字符串。
        /// </summary>
        public static string IdleWhenWindowsLock {
            get {
                return ResourceManager.GetString("IdleWhenWindowsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置 的本地化字符串。
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按下 ESC 键显示密码框 的本地化字符串。
        /// </summary>
        public static string KeyboardDownActivePwd {
            get {
                return ResourceManager.GetString("KeyboardDownActivePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色 的本地化字符串。
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定行为 的本地化字符串。
        /// </summary>
        public static string Lock_Group_Behavior {
            get {
                return ResourceManager.GetString("Lock_Group_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示与交互 的本地化字符串。
        /// </summary>
        public static string Lock_Group_Display {
            get {
                return ResourceManager.GetString("Lock_Group_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁提示 的本地化字符串。
        /// </summary>
        public static string Lock_Group_Tips {
            get {
                return ResourceManager.GetString("Lock_Group_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 集成 的本地化字符串。
        /// </summary>
        public static string Lock_Group_WindowsIntegration {
            get {
                return ResourceManager.GetString("Lock_Group_WindowsIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定和解锁时显示动画 的本地化字符串。
        /// </summary>
        public static string LockAnimation {
            get {
                return ResourceManager.GetString("LockAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已锁定 的本地化字符串。
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁屏快捷键 的本地化字符串。
        /// </summary>
        public static string LockHotkey {
            get {
                return ResourceManager.GetString("LockHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁屏失败：请先设置锁屏快捷键 的本地化字符串。
        /// </summary>
        public static string LockHotkeyUndefined {
            get {
                return ResourceManager.GetString("LockHotkeyUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序启动时锁定屏幕 的本地化字符串。
        /// </summary>
        public static string LockOnStartup {
            get {
                return ResourceManager.GetString("LockOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁屏设置 的本地化字符串。
        /// </summary>
        public static string LockOptions {
            get {
                return ResourceManager.GetString("LockOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁屏状态提示方式 的本地化字符串。
        /// </summary>
        public static string LockStatusDisplay {
            get {
                return ResourceManager.GetString("LockStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶部呼吸灯 的本地化字符串。
        /// </summary>
        public static string LockStatusDisplayBreathingTop {
            get {
                return ResourceManager.GetString("LockStatusDisplayBreathingTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左上角圆点 的本地化字符串。
        /// </summary>
        public static string LockStatusDisplayDotTopLeft {
            get {
                return ResourceManager.GetString("LockStatusDisplayDotTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右上角圆点 的本地化字符串。
        /// </summary>
        public static string LockStatusDisplayDotTopRight {
            get {
                return ResourceManager.GetString("LockStatusDisplayDotTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不提示 的本地化字符串。
        /// </summary>
        public static string LockStatusDisplayNone {
            get {
                return ResourceManager.GetString("LockStatusDisplayNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序锁定时操作电脑显示解锁提示 的本地化字符串。
        /// </summary>
        public static string LockTips {
            get {
                return ResourceManager.GetString("LockTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷键解锁时，按下键盘不会提示 的本地化字符串。
        /// </summary>
        public static string LockTipsRemark {
            get {
                return ResourceManager.GetString("LockTipsRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先解锁 的本地化字符串。
        /// </summary>
        public static string LockTipsValue {
            get {
                return ResourceManager.GetString("LockTipsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志文件 的本地化字符串。
        /// </summary>
        public static string LogFiles {
            get {
                return ResourceManager.GetString("LogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟后 的本地化字符串。
        /// </summary>
        public static string MinAfter {
            get {
                return ResourceManager.GetString("MinAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （0 表示不启用） 的本地化字符串。
        /// </summary>
        public static string MinSetTip {
            get {
                return ResourceManager.GetString("MinSetTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击屏幕上设置的密码框位置显示密码框 的本地化字符串。
        /// </summary>
        public static string MouseDownActivePwd {
            get {
                return ResourceManager.GetString("MouseDownActivePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络请求失败，请稍后再试。 的本地化字符串。
        /// </summary>
        public static string NetworkRequestFailed {
            get {
                return ResourceManager.GetString("NetworkRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看文件 的本地化字符串。
        /// </summary>
        public static string OpenLogs {
            get {
                return ResourceManager.GetString("OpenLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        public static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码与确认密码不一致 的本地化字符串。
        /// </summary>
        public static string PasswordInconsistent {
            get {
                return ResourceManager.GetString("PasswordInconsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用密码解锁 的本地化字符串。
        /// </summary>
        public static string PasswordUnlock {
            get {
                return ResourceManager.GetString("PasswordUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码框在主屏幕中的位置 的本地化字符串。
        /// </summary>
        public static string PwdLocation {
            get {
                return ResourceManager.GetString("PwdLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要删除所有日志吗？ 的本地化字符串。
        /// </summary>
        public static string RemoveLogsConfirm {
            get {
                return ResourceManager.GetString("RemoveLogsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志已删除 的本地化字符串。
        /// </summary>
        public static string RemoveLogsOk {
            get {
                return ResourceManager.GetString("RemoveLogsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置程序设置 的本地化字符串。
        /// </summary>
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要重置所有设置并重启程序吗？ 的本地化字符串。
        /// </summary>
        public static string ResetSettingsMessage {
            get {
                return ResourceManager.GetString("ResetSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置成功 的本地化字符串。
        /// </summary>
        public static string SaveOk {
            get {
                return ResourceManager.GetString("SaveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置密码 的本地化字符串。
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string SetPasswordFinished {
            get {
                return ResourceManager.GetString("SetPasswordFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码 的本地化字符串。
        /// </summary>
        public static string SetPasswordInput {
            get {
                return ResourceManager.GetString("SetPasswordInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示主窗口 的本地化字符串。
        /// </summary>
        public static string ShowMainWindow {
            get {
                return ResourceManager.GetString("ShowMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关机 的本地化字符串。
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建议开启 的本地化字符串。
        /// </summary>
        public static string SuggestedToEnable {
            get {
                return ResourceManager.GetString("SuggestedToEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随系统 的本地化字符串。
        /// </summary>
        public static string SystemTheme {
            get {
                return ResourceManager.GetString("SystemTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 透明锁屏 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左上 的本地化字符串。
        /// </summary>
        public static string TopLeft {
            get {
                return ResourceManager.GetString("TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右上 的本地化字符串。
        /// </summary>
        public static string TopRight {
            get {
                return ResourceManager.GetString("TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已解锁 的本地化字符串。
        /// </summary>
        public static string UnLocked {
            get {
                return ResourceManager.GetString("UnLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁快捷键 的本地化字符串。
        /// </summary>
        public static string UnlockHotkey {
            get {
                return ResourceManager.GetString("UnlockHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁屏失败：请先设置解锁快捷键 的本地化字符串。
        /// </summary>
        public static string UnlockHotkeyUndefined {
            get {
                return ResourceManager.GetString("UnlockHotkeyUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁方式 的本地化字符串。
        /// </summary>
        public static string UnlockOptions {
            get {
                return ResourceManager.GetString("UnlockOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁屏失败：请先设置解锁密码 的本地化字符串。
        /// </summary>
        public static string UnlockPasswordUndefined {
            get {
                return ResourceManager.GetString("UnlockPasswordUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用锁屏快捷键 的本地化字符串。
        /// </summary>
        public static string UseLockHotkey {
            get {
                return ResourceManager.GetString("UseLockHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新记录 的本地化字符串。
        /// </summary>
        public static string VersionHistory {
            get {
                return ResourceManager.GetString("VersionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误 的本地化字符串。
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
