name: release-job

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: # ✅ 支持手动触发

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore .\src

      - name: Build
        run: dotnet build .\src --no-restore -c release

      - name: Publish
        run: dotnet publish .\src -c Release -r win-x64 -p:PublishReadyToRun=true --self-contained false

      - name: Get version
        uses: olegtarasov/get-tag@v2.1.4
        id: tagName

      - name: Create zip
        shell: pwsh
        run: Compress-Archive -Path ${{github.workspace}}\src\ComputerLock\bin\Release\net8.0-windows\win-x64\publish\* -DestinationPath ${{github.workspace}}\src\ComputerLock\bin\Release\ComputerLock_${{ steps.tagName.outputs.tag }}_win_x64.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          body_path: ${{github.workspace}}\CHANGELOG.md
          files: ${{github.workspace}}\src\ComputerLock\bin\Release\ComputerLock_${{ steps.tagName.outputs.tag }}_win_x64.zip
