name: release-job

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: # ✅ 支持手动触发

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有标签和历史记录
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore .\src

      - name: Build
        run: dotnet build .\src --no-restore -c Release

      - name: Publish
        run: dotnet publish .\src\ComputerLock\ComputerLock.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish

      - name: Get version
        uses: olegtarasov/get-tag@v2.1.4
        id: tagName

      - name: Create zip
        shell: pwsh
        run: Compress-Archive -Path ${{github.workspace}}\publish\* -DestinationPath ${{github.workspace}}\ComputerLock_${{ steps.tagName.outputs.tag }}_win_x64.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          tag_name: ${{ github.ref_name }} # 明确指定标签名
          name: Release ${{ github.ref_name }}
          body_path: ${{github.workspace}}\CHANGELOG.md
          files: ${{github.workspace}}\ComputerLock_${{ steps.tagName.outputs.tag }}_win_x64.zip